[build]
  # 构建命令
  command = "npm run docs:build"
  # 发布目录
  publish = "docs/.vitepress/dist"
  # Node.js 版本
  environment = { NODE_VERSION = "20" }

# 环境变量
[build.environment]
  VITEPRESS_BASE = "/"

# 重定向规则（SPA支持）
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# 缓存优化
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# 开发预览配置
[dev]
  command = "npm run docs:dev"
  port = 5173
  
# 构建设置
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = true