# Cloudflare Pages 配置文件
# 此文件主要用于 Wrangler CLI 部署
# 对于控制面板部署，请参考 DEPLOYMENT.md 中的手动配置说明

name = "ais-docs"
compatibility_date = "2024-01-01"

# 页面配置
pages_build_output_dir = "docs/.vitepress/dist"

# 环境变量配置
[env.production.vars]
VITEPRESS_BASE = "/"

[env.preview.vars]
VITEPRESS_BASE = "/"